name: Sync Snyk Projects

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "snyk-projects.yml"

jobs:
  sync-snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run sync script
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: python scripts/sync-snyk-projects.py
